services:
  agent-zero:
    container_name: agent-zero
    build:
      context: .
      dockerfile: Dockerfile  # o ajusta si está en subcarpeta como ./docker/run/Dockerfile
      args:
        BRANCH: main
    volumes:
      - ./agent-zero:/a0
    ports:
      - "50080:80"
