version: "3.8"

services:
  agent-zero:
    container_name: agent-zero
    build:
      context: .  # ESTO es clave, usar "." porque ya estás en docker/run
      dockerfile: Dockerfile
      args:
        BRANCH: main
    ports:
      - "50080:80"
    volumes:
      - ./agent-zero:/a0
